---
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        language_version: python3.11

  #  - repo: https://github.com/PyCQA/bandit
  #    rev: 1.6.2
  #    hooks:
  #      - id: bandit
  #        args:
  #          - "--exclude=src/javascript"

  #- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  #rev: v0.1.11
  #hooks:
  # Run the linter.
  #- id: ruff
  #  args: [--fix]
  # Run the formatter.
  #- id: ruff-format

  - repo: https://github.com/bemeurer/beautysh
    rev: 6.0.1
    hooks:
      - id: beautysh

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
